flyway:
  enabled: true
  schemas: EmployeeHistory
  locations: classpath:/sql

  spring.flyway.baselineOnMigrate: true
server:
  port: 8189
  servlet:
    context-path: /market
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courcedb
    username: postgres
    password: postgres
#    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
  #    username: sa
  #    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
#        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false